Repository apify/apify-shared-js, pull requests merged in 2022-12, with the labels that each got.

#352 feat(consts): add USER_PERSONA_TYPES const
  packages/consts/src/consts.ts
Labels: t-console

#353 chore(ci): replace `npm ci` with npm `i` in publish step
  .github/workflows/test_and_release.yml
  CHANGELOG.md
  package-lock.json
Labels: t-console

#354 feat(consts): adding CLI to META_ORIGINS
  packages/consts/src/consts.ts
Labels: t-c&c

#355 feat(consts): increase max length of actor job log to 10 MB
  packages/consts/src/consts.ts
Labels: adhoc, t-platform
