Repository apify/apify-shared-js, pull requests merged in 2022-10, with the labels that each got.

#338 feat(consts,log): add support for reading log level from env var
  packages/consts/src/consts.ts
  packages/log/src/log.ts
  packages/log/src/log_consts.ts
  packages/log/src/log_helpers.ts
Labels: enhancement, adhoc, t-platform

#340 feat(input_secrets): add new package to encrypt and decrypt input secrets
  package-lock.json
  packages/input_secrets/CHANGELOG.md
  packages/input_secrets/package.json
  packages/input_secrets/src/index.ts
  packages/input_secrets/src/input_secrets.ts
  packages/input_secrets/tsconfig.build.json
  packages/input_secrets/tsconfig.json
  packages/input_secrets/tsup.config.ts
  test/input_secrets.test.ts
Labels: t-platform

#342 chore(consts): add env vars for input secrets
  packages/consts/src/consts.ts
Labels: t-platform

#335 feat(input_schema): add isSecret flag into the sting property
  packages/input_schema/src/schema.json
  test/input_schema.test.ts
  test/input_schema_definition.test.ts
Labels: t-platform

#345 fix(markdown): marked package named imports
  packages/markdown/src/marked.ts
Labels: bug, t-web

#350 feat(consts): Adding new META_ORIGINS for jobs initiated by another actor or webhook
  packages/consts/src/consts.ts
Labels: t-platform
