Repository apify/apify-shared-js, pull requests merged in 2022-01, with the labels that each got.

#272 fix: consecutive dots in email are not allowed
  packages/consts/src/regexs.ts
  test/regexs.test.ts
Labels: bug

#277 feat(consts): added deprecated base images still used by some actors
  packages/consts/src/consts.ts
Labels: bug, adhoc

#278 fix(web): md to tab title for Javascript
  packages/markdown/src/marked.ts
  test/marked.test.ts
Labels: bug, adhoc

#279 feat(consts): remove unused consts
  packages/consts/src/consts.ts
Labels: adhoc, debt
