Repository apify/apify-shared-js, pull requests merged in 2023-04, with the labels that each got.

#376 feat!: Removing unused ACTOR_BASE_DOCKER_IMAGES and ACTOR_BASE_DOCKER_IMAGE_DEFAULT constants
  packages/consts/src/consts.ts
Labels: adhoc, debt, t-platform

#378 feat(app): Lead generation actor category
  packages/consts/src/consts.ts
Labels: t-web

#379 feat(utilities): add `MONGODB_PING` and `REDIS_PING` check types to `HealthChecker`
  packages/utilities/src/health_checker.ts
Labels: adhoc, t-platform

#380 feat: add ACTOR_MAX_PAID_DATASET_ITEMS to env vars
  packages/consts/src/consts.ts
Labels: t-c&c
