Repository apify/apify-shared-js, pull requests merged in 2023-06, with the labels that each got.

#394 feat(consts): add `ACTOR_BUILD_ARGS` const
  packages/consts/src/consts.ts
Labels: adhoc, t-platform

#396 feat: added multiselect option to input schema
  packages/input_schema/src/schema.json
Labels: t-console

#397 fix: Fixed broken array input definition
  packages/input_schema/src/schema.json
Labels: bug, adhoc, t-console

#393 feat: increase build memory size
  packages/consts/src/consts.ts
Labels: adhoc, t-console
