Repository apify/apify-shared-js, pull requests merged in 2023-03, with the labels that each got.

#363 feat: add max items to env variable names
  packages/consts/src/consts.ts
Labels: adhoc, t-c&c

#364 feat: increase default number of actors and tasks
  packages/consts/src/consts.ts
Labels: t-c&c

#373 chore: unify YAML file extensions to .yaml
  .github/workflows/check_pr_title.yaml
  .github/workflows/pr_toolkit.yaml
  .github/workflows/test_and_release.yaml
  README.md
Labels: t-platform
