Repository apify/apify-shared-js, pull requests merged in 2023-05, with the labels that each got.

#382 fix(input_schema): disallow empty `enum`s in input schema
  packages/input_schema/src/schema.json
  test/input_schema.test.ts
Labels: bug, adhoc, t-platform

#369 feat: allow using variables in fields of webhook payload template
  packages/utilities/src/webhook_payload_template.ts
  test/webhook_payload_template.test.ts
Labels: adhoc, t-console

#386 feat(utilities): add new helpers for "run on apify" button
  packages/utilities/src/index.ts
  packages/utilities/src/url_params_utils.ts
  test/url-params-utils.test.ts
Labels: t-tooling

#387 feat(utilities): use base64 encoding in url params utils
  packages/utilities/src/url_params_utils.ts
  test/url-params-utils.test.ts
Labels: adhoc, t-console

#389 fix: omits node: import from events builtin module
  packages/log/src/logger.ts
Labels: adhoc, t-platform

#388 chore: removed unused env var
  packages/consts/src/consts.ts
Labels: t-c&c

#390 chore: updated CI secrets
  .github/workflows/test_and_release.yaml
Labels: adhoc, t-platform

#392 feat: allow custom proxies to be https
  packages/consts/src/regexs.ts
  packages/input_schema/src/intl.ts
  test/utilities.client.test.ts
Labels: adhoc, t-console
