Repository apify/apify-shared-js, pull requests merged in 2024-12, with the labels that each got.

#491 feat(consts): add open source actor category
  packages/consts/src/consts.ts
Labels: t-c&c

#492 feat(utilities): markedSetNofollowLinks with hostname check
  packages/utilities/src/utilities.client.ts
  test/utilities.client.test.ts
Labels: t-console, tested

#494 feat: add `ACTOR_BUILD_TAGS`, `ACTOR_FULL_NAME` environment variables
  packages/consts/src/consts.ts
Labels: adhoc, t-platform
