Repository apify/apify-shared-js, pull requests merged in 2024-01, with the labels that each got.

#428 chore: log cause when logging exceptions
  packages/datastructures/src/lru_cache.ts
  packages/log/src/logger_text.ts
  packages/utilities/src/webhook_payload_template.ts
  scripts/create-tsup-config.ts
  test/logger_text.test.ts
  tsconfig.build.json
Labels: t-tooling, tested

#431 feat(consts): add REQUEST_QUEUE_MAX_REQUESTS_PER_BATCH_OPERATION
  packages/consts/src/consts.ts
Labels: adhoc, t-platform

#434 fix(rollback): revert logging the `cause` property from errors
  packages/input_schema/src/intl.ts
  packages/log/src/logger_text.ts
  test/logger_text.test.ts
Labels: adhoc, high priority

#430 fix: properly bundle to esm/cjs
  .github/workflows/test_and_release.yaml
  lerna.json
  package-lock.json
  package.json
  packages/consts/package.json
  packages/consts/tsup.config.ts
  packages/datastructures/package.json
  packages/datastructures/tsup.config.ts
  packages/git/package.json
  packages/git/tsup.config.ts
  packages/image_proxy_client/package.json
  packages/image_proxy_client/tsup.config.ts
  packages/input_schema/package.json
  packages/input_schema/scripts/copy-schema.ts
  packages/input_schema/tsup.config.ts
  packages/input_secrets/package.json
  packages/input_secrets/tsup.config.ts
  packages/log/package.json
  packages/log/tsup.config.ts
  packages/markdown/package.json
  packages/markdown/tsup.config.ts
  packages/payment_qr_codes/package.json
  packages/payment_qr_codes/src/czk_payment_qr_codes.ts
  packages/payment_qr_codes/tsup.config.ts
  packages/pseudo_url/package.json
  packages/pseudo_url/tsup.config.ts
  packages/salesforce_client/package.json
  packages/salesforce_client/tsup.config.ts
  packages/timeout/package.json
  packages/timeout/tsup.config.ts
  packages/utilities/package.json
  packages/utilities/tsup.config.ts
  scripts/copy.ts
  scripts/create-tsup-config.ts
  scripts/tsup.config.ts
Labels: t-tooling

#438 feat: log error causes (without breaking things this time)
  packages/log/src/log.ts
  packages/log/src/log_consts.ts
  packages/log/src/log_helpers.ts
  packages/log/src/logger.ts
  packages/log/src/logger_json.ts
  packages/log/src/logger_text.ts
  packages/log/src/node_internals.ts
  packages/utilities/src/exponential_backoff.ts
  test/exponential_backoff.test.ts
  test/log.test.ts
  test/log_helpers.test.ts
  test/logger_text.test.ts
Labels: adhoc
