Repository apify/apify-shared-js, pull requests merged in 2024-10, with the labels that each got.

#479 feat(consts): deprecate default standby port, add standby URL
  packages/consts/src/consts.ts
Labels: t-platform

#481 chore: update dependencies
  package-lock.json
  package.json
  renovate.json
  tsconfig.build.json
Labels: adhoc, t-tooling

#482 fix(input_schema): disable datepicker validation
  packages/input_schema/src/utilities.ts
  test/utilities.client.test.ts
Labels: adhoc, t-console, tested

#480 feat: add max cost per run
  packages/consts/src/consts.ts
Labels: t-c&c

#483 fix(input_schema): disable isSecret for array properties
  packages/input_schema/src/schema.json
  test/input_schema_definition.test.ts
Labels: bug, t-console, tested
