Repository apify/apify-shared-js, pull requests merged in 2024-07, with the labels that each got.

#464 fix(consts): updated linkedin profile regex to support underscore and dash in the username
  packages/consts/src/regexs.ts
  test/regexs.test.ts
Labels: bug, adhoc, t-web, tested

#465 feat(consts): add actor standby consts
  packages/consts/src/consts.ts
  test/consts.test.ts
Labels: adhoc, t-platform, tested

#466 feat: add input schema type
  packages/input_schema/src/index.ts
  packages/input_schema/src/input_schema.ts
  packages/input_schema/src/types.ts
Labels: t-c&c
