Repository apify/apify-shared-js, pull requests merged in 2024-06, with the labels that each got.

#459 feat: improve linkedin profile regex
  packages/consts/src/regexs.ts
  test/regexs.test.ts
Labels: bug, adhoc, t-c&c, tested

#460 feat: add prefill option to input schema
  packages/input_schema/src/schema.json
Labels: adhoc, t-console

#461 fix(input-schema): replace escaya with acorn
  package-lock.json
  packages/input_schema/package.json
  packages/input_schema/scripts/fix-esm.ts
  packages/input_schema/src/utilities.ts
  test/utilities.test.ts
Labels: adhoc, t-tooling, tested
