Repository apify/apify-shared-js, pull requests merged in 2025-04, with the labels that each got.

#508 chore: update eslint to v9
  .eslintrc
  eslint.config.mjs
  package-lock.json
  package.json
  packages/datastructures/src/list_dictionary.ts
  packages/image_proxy_client/src/image_proxy_client.ts
  packages/input_schema/src/input_schema.ts
  packages/input_schema/src/types.ts
  packages/input_schema/src/utilities.ts
  packages/input_secrets/src/input_secrets.ts
  packages/log/src/index.ts
  packages/log/src/log.ts
  packages/log/src/log_helpers.ts
  packages/log/src/logger.ts
  packages/log/src/logger_json.ts
  packages/log/src/logger_text.ts
  packages/markdown/src/markdown_renderers.ts
  packages/markdown/src/marked.ts
  packages/timeout/src/index.ts
  packages/utilities/src/code_hash_manager.ts
  packages/utilities/src/crypto.ts
  packages/utilities/src/hmac.ts
  packages/utilities/src/parse_jsonl_stream.ts
  packages/utilities/src/streams_utilities.ts
  packages/utilities/src/utilities.client.ts
  packages/utilities/src/utilities.ts
  packages/utilities/src/webhook_payload_template.ts
  test/consts.test.ts
  test/crypto.test.ts
  test/exponential_backoff.test.ts
  test/health_checker.test.ts
  test/input_schema.test.ts
  test/input_schema_definition.test.ts
  test/input_secrets.test.ts
  test/list_dictionary.test.ts
  test/log.test.ts
  test/log_helpers.test.ts
  test/logger_json.test.ts
  test/logger_text.test.ts
  test/lru_cache.test.ts
  test/markdown_renderers.test.ts
  test/parse_jsonl_stream.test.ts
  test/timeout.test.ts
  test/utilities.client.test.ts
  test/utilities.test.ts
  test/webhook_payload_template.test.ts
Labels: adhoc, t-tooling, tested

#509 feat: fileUrl as string editor type
  packages/input_schema/src/schema.json
  packages/input_schema/src/types.ts
  test/input_schema.test.ts
Labels: adhoc, t-console, tested

#511 feat(consts): add user env vars for tiered pricing
  packages/consts/src/consts.ts
Labels: t-c&c
